config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#top'

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  get 'game/:id' => 'folders#game'

  resources :folders do
    resources :posts
    resources :likes, only: %i[create destroy]
  end
end

app/models/folder.rb
# frozen_string_literal: true

class Folder < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy

  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  validates :title, presence: true
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :logged_in_user, only: %i[new create destroy]
  before_action :correct_user, only: [:edit]

  def index
    @folders = Folder.order(created_at: :desc).all.page(params[:page]).per(6)
  end

  def new
    @folder = Folder.new
  end

  def create
    @folder = current_user.folders.build(folder_params)
    if @folder.save
      flash[:notice] = "「#{@folder.title}」を投稿しました。"
      redirect_to new_folder_post_path(@folder)
    else
      flash[:alert] = 'フォルダ名を入力してください。'
      redirect_to new_folder_path(@folder)
    end
  end

  def destroy
    @folder = Folder.find(params[:id])
    @folder.destroy
    flash[:notice] = "「#{@folder.title}」を削除しました。"
    redirect_to user_path(current_user)
  end

  def edit
    @folder = Folder.find(params[:id])
  end

  def update
    @folder = Folder.find(params[:id])
    if @folder.save
      flash[:notice] = "フォルダ名を「#{@folder.title}」に変更しました"
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end

  def game
    @folder = Folder.find(params[:id])
  end

  def show
    @folder = Folder.find(params[:id])
    @random = @folder.posts.order('RAND()').limit(1)
  end

  private

  def folder_params
    params.require(:folder).permit(:title)
  end
end

app/helpers/folders_helper.rb
# frozen_string_literal: true

module FoldersHelper
end

app/views/folders/_listfolder.html.erb
<% folders.each do |folder| %>
    <div class="card mx-auto">
      <div class="card-body">
        <span class="user-name">
          <% if folder.user.avatar? %>
            <%= link_to (image_tag folder.user.avatar.to_s, class:"icon"), user_path(folder.user) %>
          <% else %>
            <%= link_to image_tag('https://topituku.s3-ap-northeast-1.amazonaws.com/default_user_image.jpg', class:"icon"), user_path(folder.user) %>
          <% end %>
          <%= link_to folder.user.name, user_path(folder.user) %>
        </span>
        <p>
        <div class="ml-3">
          <p>
          <div class="ml-3">
            <span class="folder-title"><%= link_to "#{folder.title}","/game/#{folder.id}" %></span>
            <span class="float-right mt-3">
              <span class="float-right">
                <span id="likes_buttons_<%= folder.id %>">
                  <%= render partial: 'likes/like', locals: { folder: folder} %>
                </span>
                <%= link_to "","/game/#{folder.id}",class: "fas fa-gamepad fa-2x fa-fw mr-2 ml-3" %>
                <%= link_to "",folder_posts_path(folder),class: "fas fa-folder-open fa-2x fa-fw mr-1" %>
                <% if folder.user == current_user %>
                  <%= link_to "",new_folder_post_path(folder),class: "far fa-plus-square fa-2x fa-fw" %>
                  <ul class="dropdwn">
                    <li ><span class="fas fa-caret-square-down fa-2x fa-fw"></span>
                      <ul class="dropdwn_menu">
                        <% if folder.user == current_user %>
                          <li><%= link_to "フォルダ名編集",edit_folder_path(folder) %></li>
                          <li><%= link_to "フォルダ削除", folder_path(folder), method: :delete %></li>
                        <% end %>
                      </ul>
                    </li>
                  </ul>
                <% end %>
              </span>
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/folders/edit.html.erb
<div class="jumbotron">
  <h1 class="display-4">フォルダ名の編集</h1>
    <%= form_with model:@folder,local:true,class: "form-inline" do |f| %>
      <%= f.text_field :title,placeholder: "フォルダ名を入力",class: "form-control w-75", autofocus: true %>
      <%= f.submit "投稿",class: "btn btn-primary submit-btn" %>
    <% end %>
</div>

app/views/folders/game.html.erb
<div class="game-page">
  <div class="mx-auto w-90 topick-box">
    <p class="game-logo">トピつく！</p>
  </div>

  <hr>
  <div class="text-center">
    <%= link_to "ゲーム開始",folder_path,class:"btn btn-info w-90 next" %>
  </div>
</div>

app/views/folders/index.html.erb
<%= render partial: 'listfolder', locals: { folders: @folders} %>
<%= paginate @folders %>

app/views/folders/new.html.erb
<div class="jumbotron">
  <h1 class="display-4">フォルダの作成</h1>
  <p  class="lead">テーマに合わせたフォルダ名をつける。</p>
    <%= form_with model:@folder,local:true,class: "form-inline" do |f| %>
      <%= f.text_field :title,placeholder: "フォルダ名を入力",class: "form-control w-75", autofocus: true %>
      <%= f.submit "投稿",class: "btn btn-primary submit-btn" %>
    <% end %>
</div>

<% 
=begin
%>
<% if @folder.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @folder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

コメントアウトしてる場所

<div class="jumbotron">
  <h2 class="folder-title" ></h2>
  <h1 class="display-4 ">フォルダにトピックを投稿しよう！</h1>
  <p  class="lead">ランダムに表示したいトピックを投稿する。</p>
    <%= form_with model:[@folder, @folder.posts.build],local:true,class: "form-inline" do |f| %>
      <%= f.text_field:content,placeholder: "トピックを入力",class: "form-control w-75" %>
      <%= f.submit "投稿",class: "btn btn-primary submit-btn" %>
    <% end %>
    <div class="text-center">
    <%= link_to "ゲーム開始",folder_path(@folder), class:"btn btn-info btn-lg game-btn" %>
    </div>
</div>


<%
=end
%>

app/views/folders/show.html.erb
<%#= 今度追加予定。jsで作成したゲームです。 %>

<script>
    'use strict';
    const num = 16;
    const winner = Math.floor(Math.random() * num); // 0 - 4

    for (let i = 0; i < num; i++) {
      const div = document.createElement('div');
      // 定数 "div"にdivダグを代入して使用できるようにしている。divタグをを表示している
      div.classList.add('box');
      // divタグにclass="box"を追加している
      div.addEventListener('click', () => {
        if (i === winner) {
          div.textContent = 'アウト';
          div.classList.add('win');
        } else {
          div.textContent = 'セーフ!';
          div.classList.add('lose');
        }
      });
      document.body.appendChild(div);
    }
</script>

<div class="game-page">
  <div class="mx-auto w-90 topick-box">
    <div class="card-body topick-box text-center">
      <% @random.each do |post| %>
        <h1 class="topick"><%= post.content %></h1>
      <% end %>
    </div>
  </div>
  <hr>
  <div class="text-center">
    <%= link_to "次のトピックへ",folder_path,class:"btn btn-info w-90 next" %>
  </div>
</div>