config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#top'

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  get 'game/:id' => 'folders#game'

  resources :folders do
    resources :posts
    resources :likes, only: %i[create destroy]
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name: "User"
	belongs_to :follower, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @follow = current_user.active_relationships.build(follower_id: params[:user_id])
    @user = User.find(params[:user_id])
    @follow_count = @user.followings.count
    @follow.save
    redirect_back(fallback_location: user_path(@user))
  end

  def destroy
    @follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    @user = User.find(params[:user_id])
    @follower_count = @user.followers.count
    @follow.destroy
    redirect_back(fallback_location: user_path(@user))
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_btn.html.erb
<div class="mb-3">
  <% if user_signed_in? && current_user != user %>
    <% if user.followed_by?(current_user) %>
      <%=link_to "フォロー中", user_relationships_path(user.id), method: :delete, class:"btn btn-primary mt-2 btn-top rounded-pill",remote: true %>
    <% else %>
      <%=link_to "フォロー", user_relationships_path(user.id), method: :post ,class:"btn btn-outline-primary mt-2 btn-top rounded-pill",remote: true %>
    <% end %>
  <% end %>
</div>

app/views/relationships/create.js.erb
$('#follow_ajax_<% @user.id %>').html("<%= j(render partial: 'relationships/follow_btn', locals: {user: @user}) %>");

app/views/relationships/destroy.js.erb
$('#follow_ajax_<% @user.id %>').html("<%= j(render partial: 'relationships/follow_btn', locals: {user: @user}) %>");