config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#top'

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  get 'game/:id' => 'folders#game'

  resources :folders do
    resources :posts
    resources :likes, only: %i[create destroy]
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :folder
  belongs_to :user

  validates_uniqueness_of :folder_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.build(folder_id: params[:folder_id])
    @folder = Folder.find(params[:folder_id])
    @like.save
  end

  def destroy
    @like = Like.find_by(folder_id: params[:folder_id], user_id: current_user.id)
    @folder = Folder.find(params[:folder_id])
    @like.destroy
  end
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in?  && current_user.already_liked?(folder) %>
  <%= link_to '', folder_like_path(folder.id,folder.likes), method: :delete, class:"fas fa-heart like",remote: true %>
<% else %>
  <% if user_signed_in?  %>
    <%= link_to '', folder_likes_path(folder.id), method: :post, class:"fas fa-heart unlike",remote: true %>
  <% else %>
    <span class="fas fa-heart unlike"></span>
  <% end %>
<% end %>
<span class="ml-1"><%= folder.likes.count %></span>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @folder.id %>').html("<%= j(render partial: 'likes/like', locals: {folder: @folder}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @folder.id %>').html("<%= j(render partial: 'likes/like', locals: {folder: @folder}) %>");